# Workflow ini akan melakukan build dan testing terhadap development app.
name: Dev Testing 🔎 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and testing
    runs-on: ubuntu-latest
    environment: dev-testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" > .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env
          
      - name: Build and Run Container
        run: |
          sudo docker compose up --build --detach pacmusic-dev

      - name: Hit Endpoint
        run: |
          sleep 10
          curl http://localhost:5000

      - name: Uninstall Driver Manager to Wipeout
        run: |
          pip uninstall webdriver-manager
            
      - name: Testing Requirements
        run: |
          pip install -r test/requirements.txt
      
      - name: Testing
        run: |
          python3 test/test.py